const composite_defaults = [
    // Object One
    FAC_COMPOSITE = {
        FAC: {
            ACTIVITY: "",
            BE_NUMBER: "",
            CATEGORY: "",
            CC: "",
            CLASS_LVL: "",
            CONDITION: "",
            COORD_BASIS: "",
            COORD_DATUM: "",
            COORD_DERIV: "",
            DOMAIN_LVL: "",
            EVAL: "",
            GRAPHIC_CC: "",
            GRAPHIC_ED_NUM: "",
            GRAPHIC_SCALE: "",
            GRAPHIC_SERIES: "",
            LAST_CHG_USERID: "",
            OPER_STATUS: "",
            OSUFFIX: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            COORD: "",
            FAC_NAME: "",
            GRAPHIC_AGENCY: "",
            GRAPHIC_ED_DATE: "",
            GRAPHIC_SHEET: "",
            REVIEW_DATE: "",
            AFFILIATION: "",
            ALLEGIANCE: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            CPFL: "",
            DECLASS_ON: "",
            ELEVATION_MSL: "",
            ELEVATION_MSL_UM: "",
            FPA: "",
            RELATIVE_RANKING: "",
            RELEASE_MARK: "",
            TDI: "",
            WAC: "",
            COORD_DATETIME: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            MAX_DEMO_USE: "",
            SYMBOL_CODE: "",
            SITE_ORIGINATOR: "",
            MIL_GRID: "",
            MIL_GRID_SYS: "",
            FAC_SK: "",
        },
        FAC_TRAIT: {
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EVAL: "",
            FAC_TRAIT: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            TRAIT_EVAL: "",
            REVIEW_DATE: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            RELEASE_MARK: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            FAC_SK: "",
            FAC_TRAIT_SK: "",
        },
        FAC_AKA: {
            AKA_TYPE: "",
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            AKA: "",
            REVIEW_DATE: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            RELEASE_MARK: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            FAC_SK: "",
            FAC_AKA_SK: "",
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            AKA: "",
            REVIEW_DATE: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            RELEASE_MARK: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            FAC_SK: "",
            FAC_AKA_SK: "",
        },
        FAC_FORM: {
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            DATETIME_LAST_CHG: "",
            REVIEW_DATE: "",
            AREA: "",
            AREA_EVAL: "",
            AREA_UM: "",
            AzIMUTH: "",
            AzIMUTH_REF: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            LENGTH: "",
            LENGTH_EVAL: "",
            LENGTH_UM: "",
            RELEASE_MARK: "",
            WIDTH: "",
            WIDTH_EVAL: "",
            WIDTH_UM: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            FAC_SK: "",
            FAC_FORM_SK: "",
        },
        FAC_ORG: {
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            ORG_TYPE: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            SECTOR: "",
            ORG_NAME: "",
            REVIEW_DATE: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            RELEASE_MARK: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            FAC_SK: "",
            FAC_ORG_SK: "",
        },
        FAC_TIE: {
            ASSOC: "",
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            REVIEW_DATE: "",
            TIE_TO_ENTITY: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            RELEASE_MARK: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            TIE_FROM_SK: "",
            TIE_TO_SK: "",
            FAC_TIE_SK: "",
        }
    },
    EQP_COMPOSITE = {
        EQP: {
            ACTIVITY: "",
            ALLEGIANCE: "",
            CC: "",
            CLASS_LVL: "",
            CONDITION: "",
            COORD_BASIS: "",
            COORD_DATUM: "",
            COORD_DERIV: "",
            DOMAIN_LVL: "",
            EQP_CODE: "",
            EQP_ID_NUM: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            LOC_REASON: "",
            OPER_STATUS: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            COORD: "",
            DATETIME_CREATED: "",
            REVIEW_DATE: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            QTY_OH: "",
            QTY_OH_EVAL: "",
            RELEASE_MARK: "",
            WAC: "",
            COORD_DATETIME: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            MAX_DEMO_USE: "",
            NOMEN: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            EQP_SK: "",
        },
        EQP_AFLD: {
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            DATETIME_LAST_CHG: "",
            REVIEW_DATE: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            LOAD_CLASS_EVAL: "",
            LOAD_CLASS_NUM: "",
            PAVEMENT_CLASS_NUM: "",
            PAVEMENT_EVAL_METHOD: "",
            PAVEMENT_PSI: "",
            PAVEMENT_SUBGRADE: "",
            PAVEMENT_TYPE: "",
            RELEASE_MARK: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            EQP_SK: "",
            EQP_AFLD_SK: ""
        },
        EQP_FORM: {
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            DATETIME_LAST_CHG: "",
            REVIEW_DATE: "",
            AREA: "",
            AREA_EVAL: "",
            AREA_UM: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            ENTRY_WIDTH: "",
            ENTRY_WIDTH_EVAL: "",
            ENTRY_WIDTH_UM: "",
            FPA: "",
            LENGTH: "",
            LENGTH_EVAL: "",
            LENGTH_UM: "",
            RELEASE_MARK: "",
            SHAPE: "",
            SURFACE: "",
            WIDTH: "",
            WIDTH_EVAL: "",
            WIDTH_UM: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            EQP_SK: "",
            EQP_FORM_SK: "",
        },
        EQP_TRAIT: {
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EQP_TRAIT: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            TRAIT_EVAL: "",
            DATETIME_LAST_CHG: "",
            REVIEW_DATE: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            RELEASE_MARK: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            EQP_SK: "",
            EQP_TRAIT_SK: "",
        },
        EQP_TIE: {
            ASSOC: "",
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            DATETIME_LAST_CHG: "",
            REVIEW_DATE: "",
            TIE_TO_ENTITY: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            RELEASE_MARK: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            TIE_FROM_SK: "",
            TIE_TO_SK: "",
            EQP_TIE_SK: "",
        },
    },
    RMK_COMPOSITES = {
        RMK: {
            CLASS_LVL: "",
            DOMAIN_LV: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATU: "",
            RES_PROD: "",
            RMK_TYPE: "",
            DATETIME_CREATED: "",
            REVIEW_DATE: "",
            RMK_NAME: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            RELEASE_MARK: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            CC: "",
            ALLEGIANCE: "",
            RMK_TEXT: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            RMK_SK: "",
        },
        RMK_TIE: {
            ASSOC: "",
            CLASS_LVL: "",
            DOMAIN_LVL: "",
            EVAL: "",
            LAST_CHG_USERID: "",
            PROD_LVL_CAP: "",
            RECORD_STATUS: "",
            RES_PROD: "",
            REVIEW_DATE: "",
            TIE_TO_ENTITY: "",
            CODEWORD: "",
            CONTROL_MARK: "",
            DECLASS_ON: "",
            FPA: "",
            RELEASE_MARK: "",
            DATETIME_LAST_INFO: "",
            DECLASS_ON_DATE: "",
            SITE_ORIGINATOR: "",
            RELIDO: "",
            TIE_FROM_SK: "",
            TIE_TO_SK: "",
            RMK_TIE_SK: "",
        },
    },
];
console.log('object one: ', composite_defaults[0].FAC_COMPOSITE)
console.log('object two: ', composite_defaults[1].EQP_COMPOSITE)
console.log('object three: ', composite_defaults[2].RMK_COMPOSITE)

// 1) 
function mergeComposites(targetComposite, ...composites){
    for(let composite of composites){
        for(let prop of Object.keys(composite)){
            if(!(prop in composite)) {
                targetComposite[prop] = composite[prop];
            }
        }
    }

    return targetComposite;
}

// 2)
const completeComposite = Object.assign({}, ...composite_defaults, ...actualComposite); // will add without checking if prop is already there and overwrite each time

function addHeaderToComposite(){
    return `<?xml version="1.0" encoding="UTF-8"?>
                <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                <soapenv:Body>
                <responseUpdateComposite xmlns="urn:midb-productionService">
                <UPDATED_COMPOSITES>`;
}

function addFooterToComposite(){
    return `</UPDATED_COMPOSITES>
                </responseUpdateComposite>
                </soapenv:Body>
            </soapenv:Envelope>`
}