GET http://localhost:5000/facComposites

###

GET http://localhost:5000/facComposites/5feca69d70f51db086484668

###

POST http://localhost:5000/facComposites
Content-Type: application/json

{
    "subscribed": "my new one"
}

###

DELETE http://localhost:5000/facComposites/5feba20564ee3b9f9c484091